### ISSUE TITLE
Add test dependencies

### ISSUE THREAD

**Issue by gdalle** [kevkevs/JADE191.jl#1]
The CI is failing because you need additional dependencies for testing

See here: https://pkgdocs.julialang.org/v1.8/creating-packages/#Adding-tests-to-the-package

**Comment by gdalle** [comment]
@kevkevs the tests are still failing despite your fix, can you see why?

**Comment by j-edwins** [comment]
The issue appears to be resolved now. The files runtests.jl and make.jl had some formatting which JuliaFormatter was very unhappy with. Seems to be fixed by 574e69b158fa1732aa8e3b52c74f2edbed983085.

**Comment by gdalle** [comment]
Then you can close the issue :)
